### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zhaodie** [I0gan/pwn_waf#1]
本地运行waf是正常的，但是nc的时候就会报错
Open log [/tmp/.waf/13_57_07_36de8.log] file failed!

**Comment by zhaodie** [comment]
懂了，pwn题目如果是利用这个命令启动的话，是无法操作其他目录，所以放tmp/.waf里面，他是无法利用的
exec /usr/sbin/chroot --userspec=1000:1000 /home/ctf ./pwn

**Comment by i0gan** [comment]
Open log [/tmp/.waf/13_57_07_36de8.log] file failed! 这个报错的话说明，没有权限，但你采用chroot到 /home/ctf的话，需要保证
/home/ctf/tmp拥有可写权限，或者你在/home/ctf目录下，找到一个有可写权限的目录，将其重新编译waf即可正常运行。

**Comment by zhaodie** [comment]
这里我把记录日志的功能关掉了，chroot 这种形式启动题目上waf还是有问题
正常ctf权限运行waf,题目是正常的
![image](https://user-images.githubusercontent.com/46781023/201565373-021f31a8-14c3-4b96-9295-07fb5c82cc0c.png)
但是如果chroot 的话就会这样
![image](https://user-images.githubusercontent.com/46781023/201565471-b0b003ad-d492-4db1-96ca-aa647247f758.png)
如果不是以chroot启动题目，直接运行这样waf就是正常的，感觉不是tmp可写的问题

**Comment by i0gan** [comment]
如果你使用chroot，默认情况下，且waf用 catch或i0gan模式，得保证被监控的程序要正确存在，例如： /home/ctf/tmp/.waf/pwn 存在，且拥有可执行权限。

**Comment by i0gan** [comment]
详情请查看： https://github.com/i0gan/pwn_waf/blob/main/README.md#0x03-add-waf-to-server

**Comment by zhaodie** [comment]
谢谢师傅可以了
